### PR TITLE
Omarluq/dependency updates

### PR DESCRIPTION
**Pull request by omarluq**

### CODE REVIEW

**Comment by omarluq** [comment]
> Thoughts on making the version bump separate from the dependency changes?

@dknox20 yes that makes way more sense, would you like it in 2 PR's or just 2 commits?

**Comment by omarluq** [comment]
@dknox20 should I add another PR that addresses Rubocop violation "`metadata['rubygems_mfa_required']` must be set to `'true'`".

**Comment by dknox20** [comment]
> > Thoughts on making the version bump separate from the dependency changes?
> 
> @dknox20 yes that makes way more sense, would you like it in 2 PR's or just 2 commits?

Hmm, Ok guess multiple PRs.  Not sure that is right but I do think the version bump should be separate in normal circumstances.

**Comment by dknox20** [comment]
@omarluq should we close or update this PR?

**Comment by omarluq** [comment]
> @omarluq should we close or update this PR?

I will close it and rework these PR's for rails 7.2 support

**Pull request closed without merging**
